name: Generate Release Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore r4ezka-release.jks \
            -alias r4ezka \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "ТВОЙ_ПАРОЛЬ" \
            -keypass "ТВОЙ_ПАРОЛЬ" \
            -dname "CN=R4ezka, OU=R4ezka, O=R4ezka, L=Dnipro, ST=Dnipropetrovsk, C=UA"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: r4ezka-release-keystore
          path: r4ezka-release.jks
