name: Create Key

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create keystore
        run: |
          keytool -genkeypair \
            -keystore r4ezka.jks \
            -alias upload \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass R4ezka2026 \
            -keypass R4ezka2026 \
            -dname "CN=R4ezka"

      - name: Give me the key
        uses: actions/upload-artifact@v4
        with:
          name: r4ezka-key
          path: r4ezka.jks
